DOMAIN = "violet_pool_controller"
CONF_API_URL = "api_url"
CONF_POLLING_INTERVAL = "polling_interval"
CONF_USE_SSL = "use_ssl"
CONF_DEVICE_NAME = "device_name"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
