# _config.yml - Jekyll Configuration for Violet Pool Controller
title: Violet Pool Controller
description: Home Assistant integration for Violet Pool Controller
theme: jekyll-theme-primer

# Exclude patterns - be very explicit
exclude:
  # Development files
  - "*.pyc"
  - "*.pyo"
  - "*.egg-info"
  - "__pycache__"
  - ".pytest_cache"
  - ".mypy_cache"
  - ".ruff_cache"
  - ".venv"
  - "venv"
  - "env"
  
  # Project files
  - "requirements.txt"
  - "requirements-dev.txt"
  - "setup.py"
  - "setup.cfg"
  - "pyproject.toml"
  - "tox.ini"
  
  # Directories - use wildcards to exclude ALL content
  - "blueprints/**"
  - "blueprints/*"
  - "blueprints"
  - "custom_components/**"
  - "custom_components/*"
  - "custom_components"
  - "tests/**"
  - "tests"
  - ".github/**"
  - ".github"
  - "node_modules/**"
  - "vendor/**"
  - "src/**"
  - "src"
  
  # Specific files in blueprints that cause issues
  - "blueprints/README.md"
  - "blueprints/*.md"

# Only include these specific files
include:
  - "README.md"
  - "CHANGELOG.md"
  - "SECURITY.md"
  - "CONTRIBUTING.md"
  - "LICENSE"
  - ".nojekyll"

# Markdown processor
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  
# Collections (none for this project)
collections: {}

# Plugin settings
plugins:
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Relative links configuration
relative_links:
  enabled: true
  collections: false

# Optional front matter
optional_front_matter:
  remove_originals: false

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: false
  collections: false