[book]
title = "Violet Pool Controller Documentation"
author = "Xerolux"
description = "Comprehensive documentation for the Violet Pool Controller integration and configuration."
multilingual = false
src = "src"  # VERY IMPORTANT: Tell mdbook where your source files are.

[build]
build-dir = "book"  # Use the default 'book' directory.
create-missing = true
use-default-preprocessors = true

[output.html]
# theme = "light"  <-- REMOVE THIS LINE. Use default theme.
# default-theme = "light" <-- REMOVE THIS LINE.  Not needed.
no-section-label = false
additional-css = []  # Keep this if you HAVE a custom.css
additional-js = []
# google-analytics = ["UA-XXXXXX-1"] # Optional: Add your GA tracking ID
favicons = [
    { rel = "icon", href = "favicon.ico" }
]
git-repository-url = "https://github.com/Xerolux/violet-hass" # Add a link to your repository
git-repository-icon = "fa-github"  #  Use a FontAwesome icon

[output.html.fold]
enable = true

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.code]
copy-button = true

[output.linkcheck]
warning-is-error = true

[preprocessor.index]
command = "mdbook-index"
