[book]
title = "Violet Pool Controller Documentation"
author = "Xerolux"
description = "Comprehensive documentation for the Violet Pool Controller integration and configuration."
multilingual = false
src = "src"  # Source directory for documentation files

[build]
build-dir = "book"  # Output directory for the built book
create-missing = true
use-default-preprocessors = true

[output.html]
no-section-label = false
additional-css = []  # Include custom CSS files here if needed
additional-js = []   # Include custom JS files here if needed
favicons = [
    { rel = "icon", href = "favicon.ico" }
]
git-repository-url = "https://github.com/Xerolux/violet-hass"  # Link to the GitHub repository
git-repository-icon = "fa-github"  # FontAwesome icon for GitHub

[output.html.fold]
enable = true

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true

[output.html.code]
copy-button = true

[output.linkcheck]
warning-is-error = true
optional = true

[preprocessor.index]
command = "mdbook-index"
