blueprint:
  name: Violet Pool - Intelligente pH-Kontrolle
  description: |
    Automatische pH-Wert Kontrolle mit intelligenter Dosierung von pH+ und pH-.
    Überwacht pH-Werte und dosiert automatisch bei Abweichungen vom Sollbereich.
  domain: automation
  source_url: https://github.com/xerolux/violet-hass/blob/main/blueprints/automation/pool_ph_control.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    ph_sensor:
      name: pH-Sensor
      description: Sensor für den aktuellen pH-Wert des Pools
      selector:
        entity:
          filter:
            - integration: violet_pool_controller
            - domain: sensor
            - device_class: ph
    ph_setpoint_entity:
      name: pH-Sollwert
      description: Number-Entity für den pH-Sollwert
      selector:
        entity:
          filter:
            - integration: violet_pool_controller
            - domain: number
    ph_minus_switch:
      name: pH- Dosierung
      description: Switch für pH-Minus Dosierung
      selector:
        entity:
          filter:
            - integration: violet_pool_controller
            - domain: switch
    ph_plus_switch:
      name: pH+ Dosierung
      description: Switch für pH-Plus Dosierung
      selector:
        entity:
          filter:
            - integration: violet_pool_controller
            - domain: switch
    ph_tolerance:
      name: pH-Toleranz
      description: Toleranzbereich um den Sollwert (±)
      default: 0.2
      selector:
        number:
          min: 0.05
          max: 0.5
          step: 0.05
          unit_of_measurement: pH
          mode: slider
    dosing_duration_ph_minus:
      name: Dosierdauer pH-
      description: Dauer der pH-Minus Dosierung in Sekunden
      default: 30
      selector:
        number:
          min: 10
          max: 300
          step: 5
          unit_of_measurement: s
          mode: box
    dosing_duration_ph_plus:
      name: Dosierdauer pH+
      description: Dauer der pH-Plus Dosierung in Sekunden
      default: 30
      selector:
        number:
          min: 10
          max: 300
          step: 5
          unit_of_measurement: s
          mode: box
    max_dosing_per_day:
      name: Max. Dosierungen pro Tag
      description: Maximale Anzahl Dosierungen pro 24h als Sicherheit
      default: 10
      selector:
        number:
          min: 3
          max: 20
          step: 1
          mode: box
    min_wait_between_dosing:
      name: Wartezeit zwischen Dosierungen
      description: Mindestwartezeit zwischen Dosierungen in Minuten
      default: 60
      selector:
        number:
          min: 30
          max: 240
          step: 15
          unit_of_measurement: min
          mode: box
    enable_pump_check:
      name: Pumpen-Check aktivieren
      description: Dosierung nur bei laufender Filterpumpe
      default: true
      selector:
        boolean:
    pump_entity:
      name: Filterpumpe (Optional)
      description: Binary Sensor oder Switch der Filterpumpe
      default: ""
      selector:
        entity:
          filter:
            - integration: violet_pool_controller
            - domain: 
                - binary_sensor
                - switch
          multiple: false
    notification_entity:
      name: Benachrichtigungs-Service (Optional)
      description: Service für Benachrichtigungen
      default: ""
      selector:
        text:

variables:
  ph_current_sensor: !input ph_sensor
  ph_target_entity: !input ph_setpoint_entity
  ph_minus_entity: !input ph_minus_switch
  ph_plus_entity: !input ph_plus_switch
  tolerance: !input ph_tolerance
  dosing_duration_minus: !input dosing_duration_ph_minus
  dosing_duration_plus: !input dosing_duration_ph_plus
  max_daily_dosing: !input max_dosing_per_day
  min_wait_minutes: !input min_wait_between_dosing
  pump_check_enabled: !input enable_pump_check
  pump_sensor: !input pump_entity
  notify_service: !input notification_entity
  
  # pH-Werte
  current_ph: "{{ states(ph_current_sensor) | float(7.2) }}"
  target_ph: "{{ states(ph_target_entity) | float(7.2) }}"
  ph_diff: "{{ current_ph - target_ph }}"
  
  # Bereiche
  ph_too_high: "{{ ph_diff > tolerance }}"
  ph_too_low: "{{ ph_diff < -tolerance }}"
  ph_ok: "{{ abs(ph_diff) <= tolerance }}"
  
  # Pumpen-Status
  pump_running: >
    {% if not pump_check_enabled or pump_sensor == "" %}
      true
    {% else %}
      {{ is_state(pump_sensor, 'on') }}
    {% endif %}
  
  # Dosier-Counter (über Input Number Helper)
  dosing_counter_today: >
    {{ states('input_number.pool_ph_dosing_counter') | int(0) }}

trigger:
  - platform: numeric_state
    entity_id: !input ph_sensor
    for:
      minutes: 10
    id: ph_changed
  - platform: time_pattern
    minutes: /15
    id: periodic_check
  - platform: state
    entity_id: !input pump_entity
    to: "on"
    for:
      minutes: 5
    id: pump_started

condition:
  - condition: template
    value_template: >
      {{ states(ph_current_sensor) not in ['unavailable', 'unknown'] and
         states(ph_target_entity) not in ['unavailable', 'unknown'] }}

action:
  - choose:
      # === pH zu hoch: pH-Minus dosieren ===
      - conditions:
          - condition: template
            value_template: "{{ ph_too_high and pump_running }}"
          - condition: template
            value_template: "{{ dosing_counter_today < max_daily_dosing }}"
          - condition: template
            value_template: >
              {{ (now() - states.automation.pool_ph_control.attributes.last_triggered | default(now() - timedelta(hours=1))) > 
                 timedelta(minutes=min_wait_minutes) }}
        sequence:
          - service: violet_pool_controller.manual_dosing
            target:
              entity_id: "{{ ph_minus_entity }}"
            data:
              duration_seconds: "{{ dosing_duration_minus }}"
          
          # Counter erhöhen
          - service: input_number.set_value
            target:
              entity_id: input_number.pool_ph_dosing_counter
            data:
              value: "{{ dosing_counter_today + 1 }}"
          
          # Benachrichtigung
          - if:
              - condition: template
                value_template: "{{ notify_service != '' }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "🔻 pH-Korrektur"
                  message: >
                    pH zu hoch: {{ '%.2f' | format(current_ph) }} → {{ '%.2f' | format(target_ph) }}
                    pH-Minus für {{ dosing_duration_minus }}s dosiert

      # === pH zu niedrig: pH-Plus dosieren ===
      - conditions:
          - condition: template
            value_template: "{{ ph_too_low and pump_running }}"
          - condition: template
            value_template: "{{ dosing_counter_today < max_daily_dosing }}"
          - condition: template
            value_template: >
              {{ (now() - states.automation.pool_ph_control.attributes.last_triggered | default(now() - timedelta(hours=1))) > 
                 timedelta(minutes=min_wait_minutes) }}
        sequence:
          - service: violet_pool_controller.manual_dosing
            target:
              entity_id: "{{ ph_plus_entity }}"
            data:
              duration_seconds: "{{ dosing_duration_plus }}"
          
          # Counter erhöhen
          - service: input_number.set_value
            target:
              entity_id: input_number.pool_ph_dosing_counter
            data:
              value: "{{ dosing_counter_today + 1 }}"
          
          # Benachrichtigung
          - if:
              - condition: template
                value_template: "{{ notify_service != '' }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "🔺 pH-Korrektur"
                  message: >
                    pH zu niedrig: {{ '%.2f' | format(current_ph) }} → {{ '%.2f' | format(target_ph) }}
                    pH-Plus für {{ dosing_duration_plus }}s dosiert

      # === Maximale Dosierungen erreicht ===
      - conditions:
          - condition: template
            value_template: "{{ not ph_ok and dosing_counter_today >= max_daily_dosing }}"
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_service != '' }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "⚠️ pH-Dosierung gestoppt"
                  message: >
                    Maximale Dosierungen ({{ max_daily_dosing }}) für heute erreicht.
                    pH: {{ '%.2f' | format(current_ph) }}, Ziel: {{ '%.2f' | format(target_ph) }}
                    Manuelle Überprüfung erforderlich!

      # === pH im Sollbereich ===
      - conditions:
          - condition: template
            value_template: "{{ ph_ok }}"
          - condition: trigger
            id: ph_changed
        sequence:
          - if:
              - condition: template
                value_template: "{{ notify_service != '' }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "✅ pH-Wert optimal"
                  message: "pH-Wert im Sollbereich: {{ '%.2f' | format(current_ph) }} (Ziel: {{ '%.2f' | format(target_ph) }})"

  # Counter um Mitternacht zurücksetzen
  - if:
      - condition: template
        value_template: "{{ now().hour == 0 and now().minute == 0 }}"
    then:
      - service: input_number.set_value
        target:
          entity_id: input_number.pool_ph_dosing_counter
        data:
          value: 0

mode: single
max_exceeded: silent
