blueprint:
  name: Pool Lighting Control
  description: Automates pool lighting based on time, sunset, or presence.
  domain: automation
  input:
    light_entity:
      name: Pool Light
      description: The pool light entity.
      selector:
        entity:
          domain: light
    sunset_offset:
      name: Sunset Offset
      description: Offset in minutes before/after sunset to turn on lights.
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 5
          unit_of_measurement: minutes
    sunrise_offset:
      name: Sunrise Offset
      description: Offset in minutes before/after sunrise to turn off lights.
      default: 0
      selector:
        number:
          min: -120
          max: 120
          step: 5
          unit_of_measurement: minutes
    presence_sensor:
      name: Presence Sensor
      description: (Optional) Binary sensor for presence detection.
      default:
      selector:
        entity:
          domain: binary_sensor
    enable_notifications:
      name: Enable Notifications
      description: Send notifications when lights are turned on or off.
      default: false
      selector:
        boolean:
    notification_service:
      name: Notification Service
      description: Service to use for notifications.
      default: persistent_notification.create
      selector:
        text:

trigger:
  - platform: sun
    event: sunset
    offset: !input sunset_offset
    id: "sunset"
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
    id: "sunrise"
  - platform: state
    entity_id: !input presence_sensor
    to: "on"
    id: "presence_detected"
    enabled: "{{ presence_sensor != '' }}"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: ["sunset", "presence_detected"]
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity
          - if:
              - condition: template
                value_template: "{{ enable_notifications }}"
            then:
              - service: "{{ notification_service }}"
                data:
                  title: "Pool Lights Turned On"
                  message: "Pool lights have been turned on."
      - conditions:
          - condition: trigger
            id: "sunrise"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity
          - if:
              - condition: template
                value_template: "{{ enable_notifications }}"
            then:
              - service: "{{ notification_service }}"
                data:
                  title: "Pool Lights Turned Off"
                  message: "Pool lights have been turned off."

mode: single