blueprint:
  name: Pool Pump Timer
  description: Automates the pool pump to turn on for a specific duration, then automatically switches to AUTO mode.
  domain: automation
  input:
    pump_entity:
      name: Pump Switch
      description: The pool pump switch entity.
      selector:
        entity:
          domain: switch
    duration:
      name: Duration
      description: How long the pool pump should run (in seconds).
      default: 1800
      selector:
        number:
          min: 10
          max: 28800
          step: 10
          mode: slider
          unit_of_measurement: seconds

trigger:
  - platform: homeassistant
    event: start

action:
  - service: violet.turn_on  # explizit dein custom-service!
    target:
      entity_id: !input pump_entity
    data:
      duration: !input duration

  - delay:
      seconds: !input duration

  - service: switch.turn_auto
    target:
      entity_id: !input pump_entity

mode: single
