name: Auto-Merge Dependabot

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v5
      
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for CI checks
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        uses: fountainhead/action-wait-for-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'validate'
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 600

      - name: Auto-approve minor/patch updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr review --approve "$PR_URL" --body "✅ Auto-approving ${{ steps.metadata.outputs.update-type }} dependency update from ${{ steps.metadata.outputs.previous-version }} to ${{ steps.metadata.outputs.new-version }}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-merge approved updates
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr merge --auto --squash "$PR_URL"
          echo "🤖 Auto-merged ${{ steps.metadata.outputs.dependency-names }} update" >> $GITHUB_STEP_SUMMARY
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ⚠️ **Major Version Update**
            
            This PR contains a major version update for `${{ steps.metadata.outputs.dependency-names }}`:
            - **From:** `${{ steps.metadata.outputs.previous-version }}`
            - **To:** `${{ steps.metadata.outputs.new-version }}`
            
            Auto-merge is disabled for major updates. Please review the changelog and test thoroughly before merging.
            
            📖 [View Changelog](${{ steps.metadata.outputs.changelog-url }})
          reactions: eyes

      - name: Label PR
        uses: actions/github-script@v7
        with:
          script: |
            const updateType = '${{ steps.metadata.outputs.update-type }}';
            const label = updateType.includes('major') ? 'dependencies-major' : 
                         updateType.includes('minor') ? 'dependencies-minor' : 
                         'dependencies-patch';
            
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label, 'dependencies']
            });
