name: Changelog CI

on:
  # Trigger workflow when a pull request is opened
  pull_request:
    types: [opened]

  # Allow manual triggering of workflow with release version input
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Run Changelog CI to update changelog file
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          # Specify the changelog file (CHANGELOG.rst)
          changelog_filename: CHANGELOG.rst
          
          # Use a custom config file for changelog settings
          config_file: changelog-ci-config.json
          
          # Pass the release version from the manual trigger input
          release_version: ${{ github.event.inputs.release_version }}
          
          # GitHub token for authentication, required for commits
          github_token: ${{ secrets.GITHUB_TOKEN }}