name: Changelog CI

on:
  pull_request:
    types: [opened]

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - uses: actions/checkout@v3

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          # Verwende CHANGELOG.rst als Changelog-Datei
          changelog_filename: CHANGELOG.rst
          # Verwende eine Konfigurationsdatei für individuelle Anpassungen
          config_file: changelog-ci-config.json
          # Git Konfigurationsdetails für den Committer
          committer_username: 'Violet Pool Bot'
          committer_email: 'bot@xerolux.de'
          # Release-Version von workflow_dispatch eingeben
          release_version: ${{ github.event.inputs.release_version }}
          # GitHub Token für die Authentifizierung
          github_token: ${{ secrets.GITHUB_TOKEN }}