name: Changelog CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Release-Tooling/changelog-ci@v1.1.2
        with:
          config_file: .github/changelog-ci-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          branch: ${{ github.head_ref }}
          commit_message: "docs: update CHANGELOG.md [skip ci]"
          file_pattern: CHANGELOG.md
