name: Greetings

on:
  pull_request_target:  # Trigger on pull request events
  issues:               # Trigger on issue events

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write        # Needed to add comments to issues
      pull-requests: write  # Needed to add comments to pull requests

    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
          issue-message: |
            Thank you for opening your first issue in this repository!
            We appreciate your contribution and will do our best to address it as soon as possible.
            Please be patient and provide as much detail as possible to help us understand the issue.
          pr-message: |
            Thank you for submitting your first pull request!
            We appreciate your contribution to this project.
            Please make sure you have followed the contribution guidelines and that your code passes all tests.
            A maintainer will review your PR shortly.
