name: HACS Validation

on:
  push:
    branches:
      - main  # Run on pushes to main
    paths:  # Only run if files in these paths change
      - 'custom_components/violet_pool_controller/**'
      - '.github/workflows/hacs-validation.yml'  # Trigger if this workflow file changes
      - 'hacs.json' # Triggers is hacs config file changes

  pull_request:
    branches:
      - main
    paths:
      - 'custom_components/violet_pool_controller/**'
      - '.github/workflows/hacs-validation.yml'
      - 'hacs.json'

  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

  workflow_dispatch:  # Allow manual runs

jobs:
  hacs:
    name: HACS Validation
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          # No need to ignore brands, HACS handles this.
          # You can ignore other specific checks if needed.
          # ignore: ""
