name: HACS Validation

on:
  push:
    branches: [main]
    paths:
      - custom_components/violet_pool_controller/**
      - .github/workflows/hacs-validation.yml
      - hacs.json
  pull_request:
    branches: [main]
    paths:
      - custom_components/violet_pool_controller/**
      - .github/workflows/hacs-validation.yml
      - hacs.json
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
