name: Validate with hassfest

on:
  push:
    branches: [main]
    paths:
      - custom_components/violet_pool_controller/**
      - .github/workflows/hassfest.yml
  pull_request:
    branches: [main]
    paths:
      - custom_components/violet_pool_controller/**
      - .github/workflows/hassfest.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
