name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Run daily at 1:30 AM UTC (adjust as needed)
  workflow_dispatch:  # Allow manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has had no recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has had no recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-issue-label: 'stale'  # Use a standard "stale" label
          stale-pr-label: 'stale'    # Use a standard "stale" label
          days-before-stale: 60        # Mark issues/PRs as stale after 60 days of inactivity
          days-before-close: 7         # Close issues/PRs 7 days after being marked as stale
          operations-per-run: 30    # Limit the number of operations per run (to avoid rate limits)
          exempt-issue-labels: 'bug, enhancement, help wanted' # Labels to exclude issues.
          exempt-pr-labels: 'work-in-progress, awaiting-review' # Labels to exclude PR's.
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.' # Message for closed issues
          close-pr-message: 'This pull request was closed because it has been stalled for 7 days with no activity' # Message for closed PRs
